//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETime_WF_EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class balance
    {
        public int Id { get; set; }
        public System.DateTime datetime { get; set; }
        public int qtty { get; set; }
        public bool sing { get; set; }
        public int userId { get; set; }
        public int activitiesId { get; set; }
    }
}
