//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NETime_WF_EF6
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class netimeContainer : DbContext
    {
        public netimeContainer()
            : base("name=netimeContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<user> userSet { get; set; }
        public virtual DbSet<categories> categoriesSet { get; set; }
        public virtual DbSet<selected_activities> selected_activitiesSet { get; set; }
        public virtual DbSet<balance> balanceSet { get; set; }
        public virtual DbSet<activities> activitiesSet { get; set; }
    }
}
